Add KoderProfileCard
silvideastora/next-kodemiapp pull request #1
Opened 2021-06-30 01:05 UTC by silvideastora

Se agrega la card del perfil del koder.

2021-07-02 03:10 UTC, arianaomi commented on components/KoderProfileCard.jsx
> +export default function KoderProfileCard() {
ponerl los props que debe aceptar este component, por ejemplo Nayeli Gutierrez deberia ser {name}

2021-07-03 07:42 UTC, arianaomi commented on components/ModuleBox.jsx
> +                  <li className='block text-xl text-center font-medium px-2 py-2 hover:text-blue-light'>Talleres</li>
crear una carpeta config y poner ahi la infromacion.

2021-07-03 07:42 UTC, arianaomi commented on components/ModuleBox.jsx
> +                </li>
Aqui también se puede utilizar un map para optimizar el código

2021-07-03 07:42 UTC, arianaomi commented on components/ModuleBox.jsx
> +import Modules from '../config/modules.json'
Este archivo se debe de importar en el componente padre y el pasarcelo a este componente, entonces este componente debe recibir una prop (un parametro) 

*Si no queda claro mandame mensaje

2021-07-05 19:03 UTC, silvideastora commented on components/ModuleBox.jsx
> +                  <li className='block text-xl text-center font-medium px-2 py-2 hover:text-blue-light'>Talleres</li>
Listo, Nao! Ya quedó

2021-07-05 19:03 UTC, silvideastora commented on components/ModuleBox.jsx
> +                </li>
tambien ya quedó el map.

2021-07-05 19:04 UTC, silvideastora commented on components/ModuleBox.jsx
> +import Modules from '../config/modules.json'
Ya quedó tambien los props :)

2021-07-06 03:08 UTC, rrortegaa reviewed
Silvi, te dejé un comentario, échale un 👀

2021-07-06 03:08 UTC, rrortegaa commented on components/KoderProfileCard.jsx
> +                <div>
en el import de la línea 4, cambiar la N de la librería por n:

``import classNames from 'classNames'``

2021-07-06 03:08 UTC, rrortegaa commented on components/KoderProfileCard.jsx
> +                        <span className='block text-center px-2 py-2'><i class="fab fa-github"></i> @gutierreznaye</span>
Prevenir el uso de " " como las que están en la clase del icon

2021-07-06 03:08 UTC, rrortegaa commented on tailwind.config.js
> +          light:'#0fff'
Silvi, en esta definición de colores es recomendable que definan un patrón para los nombres:
- **dark, darker, light, lighter, etc.  ó  100, 200, 300, ..., 900**

También sería bueno que consideraras esto:
- **En cada color es posible definir el valor DEFAULT del mismo, i.e.:**
```
colors: {
  'black-kodemiapp': {
    DEFAULT: '#181818',
    100: '....',    // Usar uno de estas formas, no ambas
    light: '...'     // Usar uno de estas formas, no ambas
  }  
}
```

2021-07-06 03:08 UTC, rrortegaa commented on tailwind.config.js
> +          900:'#181818'
**lo mismo del comentario de** ⬆️

2021-07-06 03:08 UTC, rrortegaa commented on components/ModuleBox.jsx
> +                  <li className=' block text-xl text-center font-medium px-2 py-2 hover:text-blue-light'>Hello koders</li>
Silvi, ¿Podrías subir el cambio donde ya solo se hace un map al array de Módulos?

2021-07-06 03:08 UTC, rrortegaa commented on components/KoderProfileCard.jsx
> +                <div>
Me parece que te sería más fácil manipular la imagen del perfil si usas una tag img en lugar de Image de Next, para hacerlo:
- Cambia el nombre de la carpeta assets por public (actualizar imports o referencias en otras partes del código que puedan marcar error porque assets ya no existe)
- Elimina el import de la línea 3 ``import profilePic ...``
- En la propiedad src de la imagen pon la ruta ``src='/images/Nayeli.png'``

Así puedes ver la imagen lista para agregarle las clases que necesites.

2021-07-06 03:08 UTC, rrortegaa commented on next.config.js
> +      domains: ['e.rpp-noticias.io'],
Silvi, ¿aquí para qué usas esta línea?

2021-07-08 04:16 UTC, rrortegaa requested changes

2021-07-08 04:16 UTC, rrortegaa commented on components/Posts.jsx
> +import classNames from 'classNames'
- Silvi la librería debe ir en minúsculas 👀

2021-07-08 04:16 UTC, rrortegaa commented on components/Posts.jsx
> +                                <img className='mx-auto rounded-full w-10 h-10 'src={post.mentorImage}/>
- Acá ya no veo la fecha del aviso 🤔 ¿Dónde quedó?

2021-07-08 04:16 UTC, rrortegaa commented on components/ResourcesContainer.jsx
> +    <li class="hover:shadow-lg flex rounded-lg">
- Habría sido ideal que subieras este componente en otra rama para que al revisar estos comments no se retrase el merge con develop de todos los demás que existen aquí :octocat: 

- ¿La card New Project es necesaria? sino es así, es mejor quitar código que no se utiliza (si lo que buscas es mostrar que podrían haber otras cards 👇🏼) 

- Podrías llenar más cards con links (simulados) para que analicen si como se ve cada card (su estilo y contenido) es lo que buscan y si, en el conjunto de todas, ésta vista también lo hace

2021-07-08 04:16 UTC, rrortegaa commented on components/Posts.jsx
> +                          {posts.map((post,index)=>(
- Falta pasar el index del array a la prop key

2021-07-08 04:16 UTC, rrortegaa commented on components/ResourcesContainer.jsx
> +      <a href="/new" class="hover:border-transparent hover:shadow-xs w-full flex items-center justify-center rounded-lg border-2 border-gray-200 text-sm font-medium py-4">
- Aquí va className, no class
- Single quotes
- Usar classNames para ordenar todas estas clases

2021-07-08 04:20 UTC, rrortegaa requested changes
### Silvi, en la pestaña  **_Files changed_**  puedes consultar los comentarios que dejé

![image](https://user-images.githubusercontent.com/20275714/124861656-9cd25900-df79-11eb-9358-0b741dd6bfb5.png)

2021-07-08 18:13 UTC, silvideastora commented on next.config.js
> +      domains: ['e.rpp-noticias.io'],
> Silvi, ¿aquí para qué usas esta línea?

No sé, solo apareció en el config de next por default

2021-07-08 18:13 UTC, silvideastora commented on components/KoderProfileCard.jsx
> +                <div>
> Me parece que te sería más fácil manipular la imagen del perfil si usas una tag img en lugar de Image de Next, para hacerlo:
> 
> * Cambia el nombre de la carpeta assets por public (actualizar imports o referencias en otras partes del código que puedan marcar error porque assets ya no existe)
> * Elimina el import de la línea 3 `import profilePic ...`
> * En la propiedad src de la imagen pon la ruta `src='/images/Nayeli.png'`
> 
> Así puedes ver la imagen lista para agregarle las clases que necesites.

Listo, ya quedó esta parte, Rose!

2021-07-08 18:15 UTC, silvideastora commented on tailwind.config.js
> +          900:'#181818'
LIsto, aplicados los cambios a los colores!

2021-07-08 18:15 UTC, silvideastora commented on components/KoderProfileCard.jsx
> +                <div>
ya revisé todos los componentes y les cambie bien la letra N.

2021-07-08 18:16 UTC, silvideastora commented on components/KoderProfileCard.jsx
> +                        <span className='block text-center px-2 py-2'><i class="fab fa-github"></i> @gutierreznaye</span>
si, me falló en algunos iconos de recursos rápidos, se los cambio.

2021-07-08 19:16 UTC, silvideastora commented on tailwind.config.js
> +          light:'#0fff'
Listo. 
Ya alinee los colores en el estilo de white-ka en DEFAULT y su variante.

2021-07-08 19:16 UTC, silvideastora commented on components/ModuleBox.jsx
> +                  <li className=' block text-xl text-center font-medium px-2 py-2 hover:text-blue-light'>Hello koders</li>
Tambien ya está listo

2021-07-08 19:17 UTC, silvideastora commented on components/Posts.jsx
> +import classNames from 'classNames'
siiii, justo ya revisé toooodos los componentes dos veces, es la costumbre, Rose, sorry, pero esta solucionado.

2021-07-08 19:17 UTC, silvideastora commented on components/Posts.jsx
> +                                <img className='mx-auto rounded-full w-10 h-10 'src={post.mentorImage}/>
Cierto, no la he agregado, subo el cambio.

2021-07-08 20:58 UTC, rrortegaa commented on next.config.js
> +      domains: ['e.rpp-noticias.io'],
🤔  que raro, no me hace sentido

2021-07-09 00:55 UTC, silvideastora commented on next.config.js
> +      domains: ['e.rpp-noticias.io'],
la borro entonces.

2021-07-09 01:17 UTC, silvideastora commented on components/ResourcesContainer.jsx
> +    <li class="hover:shadow-lg flex rounded-lg">
ya cree la branch de admin-profile

2021-07-09 01:19 UTC, silvideastora commented on components/Posts.jsx
> +                          {posts.map((post,index)=>(
listo , ya quedó

2021-07-13 04:56 UTC, rrortegaa approved these changes

2021-07-13 04:58 UTC, merged