Index
silvideastora/next-kodemiapp pull request #2
Opened 2021-07-02 03:11 UTC by aaronbarcenas

Se crearon pantalla de Index, Login navbar y footer

2021-07-03 07:49 UTC, arianaomi commented on components/Icons.jsx
> +      <Image src={linkedin} alt="linkedin-icon" />
esto se puede optimizar con un map  y para el arl podria ser 
`alt={`${nameIcon}-icon`}`

2021-07-03 07:49 UTC, arianaomi commented on pages/index.jsx
> +      <body className="bg-black">
aqui no seria body porq por default ya todo lo que creemos en react va dentro de body entonces cambialo por section o div, yo diria que seria mejor section

2021-07-03 07:49 UTC, arianaomi commented on pages/login.jsx
> +      <body className="bg-black">
lo mismo que arriba

2021-07-06 03:05 UTC, rrortegaa requested changes
Aaron, checa los comentarios que te dejé 😉

2021-07-06 03:05 UTC, rrortegaa commented on components/Footer.jsx
> +            <NavItem href="/featured">
Quitar " " en esta línea

2021-07-06 03:05 UTC, rrortegaa commented on components/Footer.jsx
> +            <NavItem href="/https://kodemia.mx/login">Alumnos </NavItem>
Quitar " " en esta línea

2021-07-06 03:05 UTC, rrortegaa commented on components/Footer.jsx
> +      <div className="sm:pl-4">
quitar " " en esta línea

2021-07-06 03:05 UTC, rrortegaa commented on components/Navbar.jsx
> +        {/* <Link href="/login">
Aaron, este código comentado, ¿piensas usarlo más adelante? sino, quítalo

2021-07-06 03:05 UTC, rrortegaa commented on config/menu.json
> +[
Este menú, ¿Dónde se presenta? no recuerdo dónde se muestra esta info

2021-07-06 03:05 UTC, rrortegaa commented on pages/index.jsx
> +              'text-center text-2xl  -mt-24'
- si tienes ``text-2xl``  (desde mobile) no necesitas poner ``md:text-2xl``
- pon en la misma línea ``text-center`` y ``md:text-left``

2021-07-06 03:05 UTC, rrortegaa commented on components/Footer.jsx
> +        <img src='/images/logo.svg' alt="Logo" className={classNames(
lo mismo de  ⬆️

2021-07-06 03:05 UTC, rrortegaa commented on components/Icons.jsx
> +
Cambia el nombre a este componente: FooterIcons  es más descriptivo y también al icons.json

2021-07-06 03:05 UTC, rrortegaa commented on components/NavItem.jsx
> +        className={`block px-1 py-2 rounded-md text-white ${isActive ? 'bg-amber-100 text-amber-700' : ''}`}
Aquí sería bueno que quitaras el ternario y ocuparas classNames, así le pasas las clases 'bg-amber-100 text-amber-700' cuando está activo

2021-07-06 03:05 UTC, rrortegaa commented on components/Navbar.jsx
> +import Image from 'next/image';
este import de Image ya no lo estás usando, cierto?

2021-07-06 03:05 UTC, rrortegaa commented on pages/index.jsx
> +            {/* <Button /> */}
Si este Button ya no va, mejor elimina esta línea

2021-07-06 03:05 UTC, rrortegaa commented on tailwind.config.js
> +          dark: '#0e0e0e',
Aquí ponte de acuerdo con Silvi para que acuerden una nomenclatura que usen ambos, si le echas un ojo a su PR, te darás cuenta que usa otros nombres p.e. black-kodemiapp y pregúntale también si usarán: dark, darker, light, lighter ó 100, 200, 300, ..., etc. como nombres de los modificadores de color

2021-07-06 03:05 UTC, rrortegaa commented on pages/login.jsx
> +              <form class='relative'>
Revisa lo de hacer este form con React Hook Form como decías y avísanos si tienes problemas con cómo te dijo Nao que podías resolver lo de los radio buttons

2021-07-06 03:05 UTC, rrortegaa commented on pages/login.jsx
> +                {/* <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
elimina los comments que no sirvan

2021-07-06 03:05 UTC, rrortegaa commented on pages/menu.jsx
> +import React from "react";
Ten cuidado con las " " XD aquí todo el archivo las lleva

2021-07-06 03:44 UTC, aaronbarcenas commented on config/menu.json
> +[
Es para el menú que viene después de inicio de sesión... tengo que revisar con Silvi donde y quien lo hará .

2021-07-06 03:44 UTC, aaronbarcenas commented on tailwind.config.js
> +          dark: '#0e0e0e',
Ok lo reviso con ella...

2021-07-06 03:46 UTC, aaronbarcenas commented on pages/menu.jsx
> +import React from "react";
Este archivo aun no lo he trabajado... posiblemente se descarte a segun se defina el flujo...

2021-07-06 06:26 UTC, rrortegaa requested changes

2021-07-06 06:26 UTC, rrortegaa commented on config/menu.json
> +[
ok, preguntales mañana

2021-07-06 06:26 UTC, rrortegaa commented on pages/menu.jsx
> +import React from "react";
ok

2021-07-08 04:56 UTC, rrortegaa requested changes
Aaron, te dejé otros comentarios 👀

2021-07-08 04:56 UTC, rrortegaa commented on config/FooterIcons.json
> +    "name": "facebbok",
- Aquí es facebook en el nombre 😉

2021-07-08 04:56 UTC, rrortegaa commented on components/Footer.jsx
> +          <p className='mt-3'>Kodemia<span>&copy</span> 2021. Todos los derechos reservados</p>
- El ícono de copyright se pondría así:
  
  ``<span> &copy;</span>``

2021-07-08 04:56 UTC, rrortegaa commented on pages/login.jsx
> +                  minLength: { value: 2, message: 'Minimo dos caracteres 2️⃣' },
- Esta leyenda no ofrece mucha ayuda, los usuarios que tenemos son direcciones de correo completas

2021-07-13 06:04 UTC, merged